export enum ImageKeyEnum {
  BootBg = 'BootBg',
  HomeBg = 'HomeBg',
  CloseIcon = 'CloseIcon',
  Loading = 'Loading',
  LobbyBg = 'LobbyBg',
  StarIcon = 'StarIcon',
  EnterIcon = 'EnterIcon',
  AcceptIcon = 'AcceptIcon',
  DeleteIcon = 'DeleteIcon',
  GameBg = 'GameBg',
  Card2OfClubs = 'Card2OfClubs',
  Card3OfClubs = 'Card3OfClubs',
  CardBack1 = 'CardBack1',
  ChipsIcon = 'ChipsIcon',
  StarOwnerIcon = 'StarOwnerIcon',
}
